day60/day60/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views
from django.views.static import serve
from day60 import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 1  注册功能
    url(r'^register/', views.register, name='_register'),
    # 2  登陆功能
    url(r'^login/', views.login, name='_login'),
    # 3  图片验证码相关
    url(r'^get_code/', views.get_code),
    # 4  首页相关
    url(r'^home/', views.home, name='_home'),
    # 5  注销功能
    url(r'^logout/', views.logout, name='_logout'),
    # 6  修改密码
    url(r'^set_pwd/', views.set_password, name='_set_pwd'),
    # 7  暴露任意后端资源配置
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),

    # 11  点赞点踩
    url(r'^up_or_down/', views.up_or_down, name='updown'),

    # 12  文章评论
    url(r'^comment/', views.comment, name='_comment'),

    # 13  后台管理
    url(r'^backend/', views.backend, name='_backend'),

    # 14 添加文章
    url(r'^add_article/', views.add_article, name='_add_article'),

    # 15 编辑器上传图片
    url(r'^upload_image/', views.upload_image, name='_upload_image'),

    # 16  修改头像
    url(r'^set_avatar/', views.set_avatar, name='_set_avatar'),

    # 8  个人站点
    url(r'^(?P<username>\w+)/$', views.site, name='_site'),
    # 9  侧边栏筛选
    url(r'^(?P<username>\w+)/(?P<condition>category|tag|archive)/(?P<param>.*)/', views.site),
    # 10  文章详情页
    url(r'^(?P<username>\w+)/article/(?P<article_id>\d+)/', views.article_detail)
]

day60/app01/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
# 用户表继承auth模块里面的auth_user


class UserInfo(AbstractUser):
    phone = models.BigIntegerField(null=True,blank=True)  # blank告诉后台管理该字段可以为空
    # 用户头像  该字段接收到用户头像文件会自动存放到avatar文件夹下 用户没有传则全部使用默认头像
    avatar = models.FileField(upload_to='avatar/',default='avatar/default.png')
    create_time = models.DateField(auto_now_add=True)

    blog = models.OneToOneField(to='Blog',null=True)  # 防止我们录入数据报错


    class Meta:
        verbose_name_plural = '用户表'

    def __str__(self):
        return self.username

class Blog(models.Model):
    site_name = models.CharField(max_length=32)
    site_title = models.CharField(max_length=64)
    # 该字段用来模拟 每个人都可以有每个人个人站点样式
    site_theme = models.CharField(max_length=64)
    class Meta:
        verbose_name_plural = 'Blog站点表'
    def __str__(self):
        return self.site_name

class Category(models.Model):
    name = models.CharField(max_length=32)

    blog = models.ForeignKey(to='Blog',null=True)
    class Meta:
        verbose_name_plural = 'Category分类表'
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=32)
    blog = models.ForeignKey(to='Blog',null=True)
    class Meta:
        verbose_name_plural = 'Tag标签表'

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=64)
    desc = models.CharField(max_length=254)
    content = models.TextField()  # 存大段文本
    create_time = models.DateField(auto_now_add=True)

    # 一对多分类表
    category = models.ForeignKey(to='Category',null=True)
    # 多对多标签表
    tags = models.ManyToManyField(to='Tag',through='Article2Tag',through_fields=('article','tag'))
    # 一对多个人站点
    blog = models.ForeignKey(to='Blog',null=True)

    # 数据库优化设计  面试可以说的点
    comment_num = models.BigIntegerField(null=True,default=0)
    up_num = models.BigIntegerField(null=True,default=0)
    down_num = models.BigIntegerField(null=True,default=0)
    class Meta:
        verbose_name_plural = 'Article文章表'
    def __str__(self):
        return self.title

class Article2Tag(models.Model):
    article = models.ForeignKey(to='Article')
    tag = models.ForeignKey(to='Tag')
    class Meta:
        verbose_name_plural = 'Article2Tag文章标签表'

class UpAndDown(models.Model):
    user = models.ForeignKey(to='UserInfo')
    article = models.ForeignKey(to='Article')
    is_up = models.BooleanField()  # 传布尔值 存0/1
    class Meta:
        verbose_name_plural = '点赞点踩表'

class Comment(models.Model):
    user = models.ForeignKey(to='UserInfo')
    article = models.ForeignKey(to='Article')
    content = models.CharField(max_length=254)
    comment_time = models.DateField(auto_now_add=True)
    # 自关联字段   根评论与子评论
    parent = models.ForeignKey(to='self',null=True)  # 该字段存的是父评论的主键值
    # 如果有值 说明当前评论是子评论  如果没有值 说明当前评论是根评论
    class Meta:
        verbose_name_plural = 'Comment评论表'

day60/templates/666.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<input type="text" value="666" id="i1">

<div id="d1">
{#tbCommentAuthor#}
</div>
<script>
    $('#a1').text($('#tbCommentAuthor').val())
</script>
</body>
</html>

day60/templates/article_detail.html
{% extends 'base.html' %}

{% block css %}
    <style>
#div_digg {
    float: right;
    margin-bottom: 10px;
    margin-right: 30px;
    font-size: 12px;
    width: 128px;
    text-align: center;
    margin-top: 10px;
}
.diggit {
    float: left;
    width: 46px;
    height: 52px;
    background: url(/static/img/upup.gif) no-repeat;
    text-align: center;
    cursor: pointer;
    margin-top: 2px;
    padding-top: 5px;
}
.buryit {
    float: right;
    margin-left: 20px;
    width: 46px;
    height: 52px;
    background: url(/static/img/downdown.gif) no-repeat;
    text-align: center;
    cursor: pointer;
    margin-top: 2px;
    padding-top: 5px;
}
.clear {
    clear: both;
}
.diggword {
    margin-top: 5px;
    margin-left: 0;
    font-size: 12px;
    color: #808080;
}
    </style>
{% endblock %}

{% block site %}
    <div>
        <h2>{{ article_obj.title }}</h2>
        {{ article_obj.content|safe }}

        <div class="clearfix">
            <div id="div_digg">
            <div class="diggit action" >
                <span class="diggnum action" id="digg_count">{{ article_obj.up_num }}</span>
            </div>
            <div class="buryit action" >
                <span class="burynum" id="bury_count">{{ article_obj.down_num }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips" style="color: red;"></div>
        </div>
        </div>

    <div>
    <p>评论列表</p>
        <hr>
        <ul class="list-group">
        {% for comment in comment_list %}
        <li class="list-group-item">   <span>#{{ forloop.counter }}楼&nbsp;&nbsp;{{ comment.comment_time|date:'Y-m-d' }} <a href="/{{ comment.user }}/">&nbsp;&nbsp;{{ comment.user }}</a></span>
            <span class="pull-right"><a  class="reply" UserName="{{ comment.user }}" CommentId="{{ comment.pk }}">回复</a></span>
            <div>
                {% if comment.parent_id %}
{#                    拿子评论父评论的用户名 #}
                    <p>@{{ comment.parent.user.username }}</p>

                {% endif %}
                {{ comment.content }}
            </div>
        </li>
            <br>
        {% endfor %}

        </ul>

    </div>

        {% if request.user.is_authenticated %}
        <div>


        <p>发表评论</p>
        <p>
    昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50" value="{{ request.user.username }}">
        </p>
        <p>评论内容</p>
        <p>
            <textarea name="content" id="id_content" cols="30" rows="10"></textarea>
        </p>
        <p>
            <button class="btn btn-primary" id="id_comment">提交评论</button>&nbsp;&nbsp;<span></span>
        </p>
    </div>
        {% else %}
            <span ><a href="{% url '_login' %}">登录&nbsp;&nbsp;</a></span>
            <span><a href=" {% url '_register' %}">注册</a></span>
        {% endif %}

    </div>


    <script>
    // 点赞点踩js代码
    $('.action').click(function () {
        var $divEle = $(this);
        $.ajax({
            url: '{% url 'updown' %}',
            type: 'post',
            data: {
                'article_id': {{ article_obj.pk }},
                'is_up': $(this).hasClass('diggit'),
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function (data) {
                if (data.code===1000){
                    $('#digg_tips').text(data.msg);
                    $divEle.children().text(Number($divEle.children().text()) + 1);
                    {##  返回被选元素旗下的所有直接子元素#}
                    {##  获取 当前元素紧邻其后的 同辈元素#}
                }else{
                    $('#digg_tips').html(data.msg)
                }
            }
        })
    });

    // 评论
    var ParentId = null;
    $('#id_comment').click(function () {
        var conTent = $('#id_content').val();
        var $btn = $(this);
        // 判断是否需要对conTent 进行处理
        if (ParentId){
            // 切割  获取第一个\n 对应的索引
            var indexN = conTent.indexOf('\n') + 1;  // 切片是顾头不顾尾的，所以索引需要加 1
            conTent = conTent.slice(indexN)  // 将indexN 之前的直接切除，只保留indexN后面的
        }
        $.ajax({
            url: '{% url "_comment" %}',
            type: 'post',
            data: {
                'article_id': {{ article_obj.pk }},
                'content': conTent,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'parent_id': ParentId
            },
            success: function (data) {
                if (data.code===1000){
                    var Userinfo = '{{ request.user.username }}';
                    var Content = $('#id_content').val();
                    // 将内容临时渲染到ul标签内
                    var temp =`
                    <li class="list-group-item">
                        {#<span> <a href="/${Userinfo}/">${Userinfo}</a> </span>#}
                        <span><span class="glyphicon glyphicon-comment"></span><a href="/${Userinfo}/">${Userinfo}</a></span>
                        <div>
                            ${Content}
                        </div>
                    </li>
                    `;
                    $('.list-group').append(temp);
                    $('#id_content').val('');

                    $btn.next().text(data.msg);
                    ParentId = null;
                }
            }
        })
    });
    // 回复功能
    $('.reply').click(function () {
        var UserName = $(this).attr('UserName');
        var Comment_Id = $(this).attr('CommentId');
        var temp = '@' + UserName + '\n';
        $('#id_content').val(temp).focus();
        ParentId = Comment_Id;
    });
    </script>
{% endblock %}

day60/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/media/css/{{ username_obj }}.css">
    {% block css %}

    {% endblock %}
    
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">{{ request.user.blog.site_title }}</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">随笔 <span class="sr-only">(current)</span></a></li>
        <li><a href="#">文字</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">更多详情</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="#">{{ request.user.username }}</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                 aria-haspopup="true" aria-expanded="false">更多操作 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-lg">修改密码</a></li>
                <li><a href="{% url '_backend' %}">后台管理</a></li>
                <li><a href="{% url '_set_avatar' %}">修改头像</a></li>
                <li><a href="{% url '_logout' %}">注销</a></li>
    {#            <li role="separator" class="divider"></li>#}
    {#            <li><a href="#">更多</a></li>#}
              </ul>
            </li>
          {% else %}
              <li><a href="{% url '_login' %}">登陆</a></li>
              <li><a href="{% url '_register' %}">注册</a></li>
          {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>
<!-- Large modal -->

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <h2 class="text-center">修改密码</h2>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="form-group">
                    <label for="">用户名</label>
                    <input type="text" name="username" value="{{ request.user.username }}" class="form-control" disabled>
                </div>
                <div class="form-group">
                    <label for="id_old_password">原密码</label>
                    <input type="text" name="old_password" class="form-control" id="id_old_password">
                </div>
                <div class="form-group">
                    <label for="id_new_password">新密码</label>
                    <input type="text" name="new_password" class="form-control" id="id_new_password">
                </div>
                <div class="form-group">
                    <label for="id_confirm_password">确认密码</label>
                    <input type="text" name="confirm_password" class="form-control" id="id_confirm_password">
                </div>
                <button class="btn btn-primary" id="id_set">确认修改</button>
                <button class="btn btn-default" data-dismiss="modal">取消</button>&nbsp;
                <span style="color: red"></span>
                <br>
                <br>
                <p></p>
                <p></p>
            </div>

        </div>
    </div>
  </div>
</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
        {% load my_tags %}
        {% my_left username %}
        </div>
        <div class="col-md-10">
        {% block site %}

        {% endblock %}
        </div>
        </div>
    </div>
{#</div>#}

<script>
    $('#id_set').click(function () {
        var $btn = $(this);
        $.ajax({
            url: '{% url "_set_pwd" %}',
            type: 'post',
            data: {
                old_pwd: $('#id_old_password').val(),
                new_pwd: $('#id_new_password').val(),
                confirm_pwd: $('#id_confirm_password').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (data) {
                if (data.code===1000) {
                    location.href = data.url
                }else {
                    $btn.next().next().text(data.msg)
                }
            }
        })
    })
</script>


</body>
</html>

day60/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <a href="http://127.0.0.1/home"><img src="/media/avatar/头像2.jpg" alt="cnblogs"></a>
    <p><b>404.</b> 抱歉，您访问的资源不存在。</p>
    <p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至 ***与我们联系。</p>
    <p><a href="http://127.0.0.1:8001/home">返回网站首页</a></p>

</body>
</html>

day60/templates/left_menu.html
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title text-center">文章分类</h3>
  </div>
  <div class="panel-body">
      {% for category in category_list %}
         <p><a href="/{{ username }}/category/{{ category.pk }}/">{{category.name}}
          ({{ category.c }})</a></p>
      {% endfor %}
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title text-center">文章标签</h3>
  </div>
  <div class="panel-body">
      {% for tag in tag_list %}
       <p>   <a href="/{{ username }}/tag/{{ tag.pk }}/">{{ tag.name }}
          ({{ tag.c }})</a></p>
      {% endfor %}
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title text-center">日期归档</h3>
  </div>
  <div class="panel-body">
      {% for date in date_list %}
      <p><a href="/{{ username }}/archive/{{ date.month|date:'Y-m' }}/">
          {{ date.month|date:'Y年m月' }}({{ date.c }})
      </a></p>
      {% endfor %}
  </div>
</div>

day60/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <h2 class="text-center">登陆</h2>
    <div class="col-md-8 col-md-offset-2">
        <form id="login_form">
            {% csrf_token %}
        <div class="form-group">

            <label for="id_username">用户名</label>
            <input type="text" name="username" class="form-control" id="id_username">
        </div>
        <div class="form-group">
            <label for="id_password">密码</label>
            <input type="password" name="password" class="form-control" id="id_password">

        </div>
        <div class="form-group">
            <label for="id_code">验证码</label>
            <div class="row">
                <div class="col-md-6">
                    <input type="text" name="code" class="form-control" id="id_code">
                </div>
                <div class="col-md-6" >
                    <img src="/get_code/" alt="" id="id_img">
                </div>
            </div>
        </div>
        <br>
        <input type="button" value="登陆" class="btn btn-primary" id="id_btn">&nbsp <span style="color: red"></span>
        </form>
    </div>
</div>

<script>
    $('#id_img').click(function () {
       var oldSrc = $(this).attr('src');
       $(this).attr('src', oldSrc += '?')
    });


    $('#id_btn').click(function () {
        var $btn = $(this);
        $.ajax({
            url:'',
            type: 'post',
            data: {
                'username': $('#id_username').val(),
                'password': $('#id_password').val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'code': $('#id_code').val(),
            },
            success: function (data) {
                if (data.code===1000){
                    location.href = data.url
                }else if (data.code===2000){
                    $btn.next().text(data.msg)
                }else {
                    $btn.next().text(data.msg)
                }
            }
        })
    })
</script>
</body>
</html>

day60/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

</body>
</html>

day60/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <h2 class="text-center">注册页面</h2>
        <div class="col-md-8 col-md-offset-2">
            <form id="myform">
                {% csrf_token %}

                {% for form in form_obj %}
                    <div class="form-group">
                        <label for="{{ form.id_for_label }}">{{ form.label }}</label>
                        {{ form }}
                        <span style="color: red" class="pull-right"></span>
                    </div>
                {% endfor %}

                <div class="form-group">
                    <label for="id_avatar">头像
                        <img src="/static/img/头像1.jpg" alt="" width="200" style="margin-left: 10px" id="id_img">
                    </label>
                    <input type="file" name="myfile" id="id_avatar" style="display: none">
                </div>
                <input type="button" value="注册" class="btn btn-primary pull-right" id="id_submit">
            </form>
        </div>
    </div>
</div>

<script>
    $('#id_avatar').change(function () {
        // 1 先获取用户上传的头像文件
        var avatarFile = $(this)[0].files[0];
        // 2 利用文件阅读器对象
        var myFileReader = new FileReader();
        // 3 将文件交由阅读器对象读取
        myFileReader.readAsDataURL(avatarFile);
        // 4 修改img标签的src属性  等待文件阅读器对象读取文件之后再操作img标签
        myFileReader.onload = function(){
            $('#id_img').attr('src',myFileReader.result)
        }

    });

    // 点击按钮触发ajax提交动作
    $('#id_submit').on('click',function () {
        // 1 先生成一个内置对象 FormData
        var myFormData = new FormData();
        // 2 添加普通键值对
        {#console.log($('#myform').serializeArray())#}
        // 循环myform里的每一个对象
        $.each($('#myform').serializeArray(),function (index,obj) {
            myFormData.append(obj.name,obj.value)
        });
        // 3 添加文件数据
        myFormData.append('avatar',$('#id_avatar')[0].files[0]);
        // 4 发送数据
        $.ajax({
            url:'',
            type:'post',
            data:myFormData,
            // 两个关键性参数
            contentType:false,
            processData:false,

            success:function (data) {
                if (data.code===1000){
                    // 注册成功之后 应该跳转到后端返回过来的url
                    location.href = data.url
                }else{
                    $.each(data.msg,function(index,obj){
                        // 1 先手动拼接字段名所对应的input框的id值
                        var targetId = '#id_' + index;  // #id_username
                        // 2 利用id选择器查找标签  并且将div标签添加报错类
                        $(targetId).next().text(obj[0]).parent().addClass('has-error')
                    })
                }
            }
        })
    });
    $('input').focus(function () {
        // 移除span标签内部的文本  还需要移除div标签的class中has-error属性
        $(this).next().text('').parent().removeClass('has-error')
    })
</script>
</body>
</html>

day60/templates/set_avatar.html
{% extends 'backend/backend_base.html' %}

{% block article %}

    <p>原头像
        <img src="/media/{{ request.user.avatar }}/" alt="">
    </p>

    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
                    <label for="id_avatar">头像
                        <img src="/static/img/头像1.jpg" alt="" width="200" style="margin-left: 10px" id="id_img">
                    </label>
                    <input type="file" name="myfile" id="id_avatar" style="display: none">
                </div>
                <input type="submit" value="提交" class="btn btn-primary pull-right" id="id_submit">

    </form>


    <script>
    $('#id_avatar').change(function () {
        // 1 先获取用户上传的头像文件
        var avatarFile = $(this)[0].files[0];
        // 2 利用文件阅读器对象
        var myFileReader = new FileReader();
        // 3 将文件交由阅读器对象读取
        myFileReader.readAsDataURL(avatarFile);
        // 4 修改img标签的src属性  等待文件阅读器对象读取文件之后再操作img标签
        myFileReader.onload = function(){
            $('#id_img').attr('src',myFileReader.result)
        }

    });
    </script>
{% endblock %}

day60/templates/site.html
{% extends 'base.html' %}

{% block site %}

            <ul class="media-list">
              {% for article in page_queryset %}
                <li class="media">
                <h4 class="media-heading"><a href="/{{ username }}/article/{{ article.pk }}/">{{ article.title }}</a></h4>
                <div class="media-left">
                  <a href="#">
                    <img class="media-object" src="/media/{{ article.blog.userinfo.avatar }}" alt="..." width="60px">
                  </a>
                </div>
                <div class="media-body">

                  {{ article.desc }}
{#                    posted @ 2019-12-29 22:42 Santa-Claus 阅读 (72) 评论 (0) 编辑#}

                </div>
                    <br>
                    <div class="pull-right">
                    <span>posted</span>
                    &nbsp;@ &nbsp;
                    <span>{{ article.create_time|date:'Y-m-d' }}</span>&nbsp;
                        &nbsp;<span>{{ article.blog.userinfo.username }}</span>&nbsp;
                        &nbsp;<span><span class="glyphicon glyphicon-hand-right"></span>点赞({{ article.up_num }})&nbsp;</span>
                        &nbsp;<span><span class="glyphicon glyphicon-comment"></span>评论({{ article.comment_num }})</span>
                        &nbsp;<span><a href="#">编辑</a></span>
                        </div>



              </li>
                  <hr>
              {% endfor %}


            </ul>
<div class="pull-right"> {{ page_obj.page_html|safe }}</div>
{% endblock %}